Some changes to start supporting Java 11
* Use OpenJFX 11
* Add annotation-api dependency
* Remove tools.jar dependency
* Use recent TestFX that accesses Robot properly

This last bullet is not quite working; even though
TestFX/TestFX#629 claims this has been fixed I continue to get
NoClassDefFoundError when trying to run tests.